test:
  stripe_api_key: 'sk_test_QvQjNczvJ1wKiAfbRt3GmPQT'
  stripe_publishable_key: 'pk_test_eXBPkJRncUJHAKMq1Y1BnhB3'
development:
  stripe_api_key: 'sk_test_QvQjNczvJ1wKiAfbRt3GmPQT'
  stripe_publishable_key: 'pk_test_eXBPkJRncUJHAKMq1Y1BnhB3'
production:
  stripe_api_key: 'sk_live_lB6OYU5zk5QF3NyGF7uplKFP'
  stripe_publishable_key: 'pk_live_iDD7pN3bSkrwZvzn5c26pivr'
development:
  bucket: thricemarketplace
  access_key_id: AKIAI4BSTR4YAHU2KPMQ
  secret_access_key: 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
test:
  bucket: thricemarketplace
  access_key_id: AKIAI4BSTR4YAHU2KPMQ
  secret_access_key: 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
production:
  bucket: thricemarketplace
  access_key_id: AKIAI4BSTR4YAHU2KPMQ
  secret_access_key: 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

# heroku config:set PUBLISHABLE_KEY=pk_live_iDD7pN3bSkrwZvzn5c26pivr SECRET_KEY=sk_live_lB6OYU5zk5QF3NyGF7uplKFP