access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
bucket: <%= ENV['S3_BUCKET_NAME'] %>
# S3_ACCESS_KEY:           'AKIAJ2DZZTZEXDRURNHA'
# S3_BUCKET_NAME:          'thricemarketplace'
# S3_SECRET_KEY:           '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'